### ISSUE TITLE
start.sh returns "unable to open output file"

### ISSUE THREAD

**Issue by tpsteiner** [blacksteed232/elexion#1]

**Comment by akphi** [comment]
@tpsteiner Have you installed all the necessary packages? start.sh is used to load the apps, some of which requires loading the CSV data files, but all just uses read.csv() from R so none should really give you an error output like _"unable to open output file."_ My guess is it has to do with this [issue](http://r.789695.n4.nabble.com/Problem-in-using-BATCH-command-td902496.html). Are you running the script on Windows? I am running my script on Mac and Ubuntu; it seems to work fine as long as you installed the packages.

> The script uses the path syntax of UNIX, you might try to modify this to work on Windows.

It will be great if you can provide me with more details. Also, another suspicion that I have has to do with the visNetwork package, since it is the only package used among the apps that actually generates an output HTML file--so if this file is somehow not reachable by the script, the mentioned error output might appear; if so you can try to modify the script to skip those visNetwork apps.

> The bash script is really just a _1-click_ collection of a chain of commands to load up the apps using 1 terminal window. You can just run one on each window and see if that works!

Thank you for the feedback.

**Comment by tpsteiner** [comment]
My PC is running Windows 10. I ran the app.R file, all packages load properly except rJava. The error I get is `Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dirname(this$RuntimeLib)
  error: a character vector argument expected`
I think the answer is located here, but this is where I gave up. Good luck!
http://stackoverflow.com/questions/7019912/using-the-rjava-package-on-win7-64-bit-with-r

**Comment by akphi** [comment]
I see. rJava gives me a hard time too! I know that at least for me, I have to install the JDK again and then run 
```
sudo R CMD javareconf
```
to make R recognize the new Java version. I think when you run that command, it will tell you what is missing from your installed version of Java that might cause a problem. After that, you can go to R and run
```
install.packages("rJava",type='source')
```

Nevertheless, as I mentioned, I really think it has nothing to do with the error you have spotted, since rJava is only needed for rWeka and FSelector packages which are used for building the output. I did point out that the problem might just be Windows does not support the R CMD command (running R directly from bash or cmd).

Try to open multiple shell windows and for each, open R shell from the ./elexion/code directory and source the file. At least, for now, you can try

```
source("start.sh")
```

It should get something going, I expect.

I don't really use windows and I think windows now support bash. Have you tried that out yet? 

I will close the issue for now. Feel free to keep me updated on the issue. If you need help, feel free to contact me again.
